### ISSUE TITLE
Deploy is broken - scss error

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/PresenceChecker#139]
```


       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/import_node.rb:65:in `import'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/import_node.rb:28:in `imported_file'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/import_node.rb:37:in `css_import?'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/perform.rb:310:in `visit_import'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/base.rb:36:in `visit'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/perform.rb:158:in `block in visit'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/stack.rb:79:in `block in with_base'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/stack.rb:135:in `with_frame'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/stack.rb:79:in `with_base'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/perform.rb:158:in `visit'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/base.rb:52:in `map'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/base.rb:52:in `visit_children'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/perform.rb:179:in `with_environment'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/perform.rb:166:in `visit_children'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/base.rb:36:in `block in visit'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/perform.rb:186:in `visit_root'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/base.rb:36:in `visit'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/perform.rb:157:in `visit'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/visitors/perform.rb:10:in `visit'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/root_node.rb:36:in `css_tree'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/tree/root_node.rb:20:in `render'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sass-3.7.2/lib/sass/engine.rb:290:in `render'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/sass_compressor.rb:48:in `call'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/sass_compressor.rb:28:in `call'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'

       /tmp/build_e2f3bcdd63b90e473d0d4dc1f6c52043/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

       Tasks: TOP => assets:precompile

       (See full trace by running task with --trace)

 !

 !     Precompiling assets failed.

 !

 !     Push rejected, failed to compile Ruby app.

 !     Push failed

```

**Comment by Br3nda** [comment]
Closing duplicate ticket
